### ISSUE TITLE
Last thing once I'd got everything else sorted

### ISSUE THREAD

**Issue by danwills** [Chakazul/Lenia#13]
I got all the dependencies installed (gentoo Linux using portage had everything apart from renia, so a local renia checkout with $PYTHONPATH specified) and then when I tried to run LeniaND.py (I was keen for the python version), I got a traceback from reikna:

File "/home/dan/dev/python/lenia/Lenia.git/Python/reikna/reikna/cluda/ocl.py", line 114, in _copy_array
    dest.set(src, queue=self._queue, async_=self._async)
TypeError: set() got an unexpected keyword argument 'async_'

I guess this should probably be reported to the reikna github (if there is one!) but I thought I might as well let you know - and yes, maybe this would have worked if I had a newer nvidia-drivers installed? (currently on 390.87) but the code could also check if that arg is allowed before passing it perhaps?.

I was able to run LeniaND.py fine after removing that single 'async' argument from the call to 'set()' mentioned above.

**Comment by bjorn3** [comment]
Which python version are you using?

**Comment by Chakazul** [comment]
I faced similar issue before, reikna's creator fixed it after I reported. I left a comment there to raise your issue.
https://github.com/fjarri/reikna/issues/30

**Comment by danwills** [comment]
Thanks for reporting that Bert! Sounds like I should update my reikna version to 0.7.3 or later, once it is released : )

Bjorn, to answer your question I currently have python-3.6.9 as my default version.
