### ISSUE TITLE
Host on GitHub pages?

### ISSUE THREAD

**Issue by textpain** [Chakazul/Lenia#18]
Hi!

First, I'm astonished of lifeforms' beauty.

It seems like there is no Webpack / Babel / other build solution involved. When I cloned the repo, I just opened `JavaScript/Lenia.html` and it worked.

Please, consider using GitHub pages to host Lenia, so everyone visiting this page could just click a link and check out Lenia for themselves, without cloning the repository.

**Comment by bjorn3** [comment]
It is already: https://chakazul.github.io/Lenia/JavaScript/Lenia.html

**Comment by mvoloskov** [comment]
That’s great. Consider adding the link into this very repo: near the repository description to the right, there’s an Edit button that allows adding a demo link.
